image: ros:dashing-ros-base-bionic

variables:
  DOCKER_DRIVER: overlay2
  GIT_CLONE_PATH: $CI_BUILDS_DIR/src/$CI_PROJECT_NAME/

before_script:
  - cd $CI_BUILDS_DIR
  - apt-get update
  - apt-get install wget
  - wget -q https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
  - vcs import src < ros2.repos
  - rm -rf src/ros2/rcl/ src/ros2/rclcpp/
  - git clone -b instrumentation --single-branch https://$DEPLOY_USERNAME_RCL:$DEPLOY_TOKEN_RCL@gitlab.com/boschresearch/ros-wg/tracing/rcl.git src/rcl/
  - git clone -b instrumentation --single-branch https://$DEPLOY_USERNAME_RCLCPP:$DEPLOY_TOKEN_RCLCPP@gitlab.com/boschresearch/ros-wg/tracing/rclcpp.git src/rclcpp/
  - apt-get install --no-install-recommends -y libasio-dev libtinyxml2-dev
  - rosdep update
  - rosdep install --from-paths src --ignore-src --rosdistro dashing -y --skip-keys "console_bridge fastcdr fastrtps libopensplice67 libopensplice69 rti-connext-dds-5.3.1 urdfdom_headers"

build:
  script:
    - pwd
    - colcon build --symlink-install --packages-up-to tracetools tracetools_test
    - pwd
    - colcon test --packages-select tracetools tracetools_test
    - find | sed 's|[^/]*/|- |g'
  artifacts:
    paths:
      - ../install
    reports:
      junit: ../build/*/Testing/*/Test.xml
      
build_enabled:
  script:
    - pwd
    - colcon build --symlink-install --cmake-args " -DWITH_LTTNG=ON" --packages-up-to tracetools tracetools_test
    - pwd
    - colcon test --packages-select tracetools tracetools_test
    - find | sed 's|[^/]*/|- |g'
  artifacts:
    paths:
      - ../install
    reports:
      junit: ../build/*/Testing/*/Test.xml
