image: registry.gitlab.com/micro-ros/ros_tracing/ros2_tracing/ci-base:latest

variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: ros2trace tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
  base_image_id: registry.gitlab.com/micro-ros/ros_tracing/ros2_tracing/ci-base

services:
  - docker:dind

before_script:
  - vcs import < instrumentation.repos

build_enabled:
  image: $base_image_id
  script:
    - lttng-sessiond --daemonize
    - . /root/ws/install/local_setup.sh
    - colcon build --symlink-install --cmake-args " -DWITH_LTTNG=ON" --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml
  except:
    - /.*docker.*/
        
ci_base_image:
  image: docker:stable
  script:
    - docker build --tag $base_image_id -f docker-ci-base/Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push $base_image_id
  only:
    - /.*docker.*/