variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: ros2trace tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
  base_image_id: registry.gitlab.com/micro-ros/ros_tracing/ci_base

image: $base_image_id

.global_artifacts: &global_artifacts
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml

before_script:
  - vcs import < instrumentation.repos
  - rosdep install --from-paths . -i . -i /root/ws --rosdistro dashing -y
  - . /root/ws/install/local_setup.sh

build_enabled:
  script:
    - lttng-sessiond --daemonize
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result
  <<: *global_artifacts

build:
  script:
    - colcon build --symlink-install --cmake-args " -DTRACETOOLS_DISABLED=ON" --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result
  <<: *global_artifacts
