variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: ros2trace tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
  base_image_id: registry.gitlab.com/micro-ros/ros_tracing/ci_base

.global_artifacts: &global_artifacts
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml

before_script:
  - vcs import < instrumented.repos
  - . /root/ws/install/local_setup.sh

tracing_enabled:
  image: $base_image_id
  script:
    - lttng-sessiond --daemonize
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - ./build/tracetools/status
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result --all
  <<: *global_artifacts

tracing_disabled:
  image: $base_image_id
  script:
    - colcon build --symlink-install --cmake-args " -DTRACETOOLS_DISABLED=ON" --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - (! ./build/tracetools/status)
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result --all
  <<: *global_artifacts

no_lttng:
  image: $base_image_id:base
  script:
    - colcon build --symlink-install --packages-up-to $PACKAGES_LIST
    - . install/local_setup.sh
    - (! ./build/tracetools/status)
    - colcon test --packages-select $PACKAGES_LIST
    - colcon test-result --all
  <<: *global_artifacts
