image: ros:dashing-ros-base

variables:
  DOCKER_DRIVER: overlay2

build:
  script:
    - rosdep update
    - rosdep install -y --from-paths . -i .
    - ln -s . src
    - apt install -y python3-colcon-ros 
    - colcon build
    - colcon test
  artifacts:
    paths:
      - install
      
build_enabled:
  script:
    - rosdep update
    - rosdep install -y --from-paths . -i .
    - ln -s . src
    - apt install -y python3-colcon-ros 
    - colcon build --cmake-args -DWITH_LTTNG=ON
    - colcon test
  artifacts:
    paths:
      - install